import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { withRouter } from "next/router";
import { Router } from "next/router";

// styles
import styles from "../../styles/Anime.module.css";

export async function getServerSideProps({ query }) {
  const { q: searchingQuery } = query;

  const res = await fetch(
    `http://api.jikan.moe/v4/anime?q=${searchingQuery}&limit=15`
  );

  const { data } = await res.json();
  if (!res.ok) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      searchingQuery,
      data,
    },
  };
}

// SearchPage.getInitialProps = async ({ params }) => {
//   console.log(params);
// };

export default function SearchPage({ data, searchingQuery }) {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>search: {searchingQuery}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.sectionHeader}>
        <h1>Searching : {searchingQuery}</h1>
        <button onClick={() => router.back()}>Back</button>
      </div>
      <div className={styles.animesContainer}>
        {data.map((anime) => {
          return (
            <div className={styles.card} key={anime.mal_id}>
              <div className={styles.rating}>{anime.score}</div>

              <img
                loading="lazy"
                src={anime.images.jpg.image_url}
                alt="img"
                className={styles.animeImage}
              />

              <div className={styles.animeContent}>
                <Link href={`/anime/${anime.mal_id}`}>
                  <h2 className={styles.title}>{anime.title}</h2>
                </Link>
              </div>
            </div>
          );
        })}
      </div>
      {/* <div className={styles.animesContainer}>
        <div className={styles.card}>
          <div className={styles.rating}>8.7</div>

          <img
            src="https://cdn.myanimelist.net/r/160x220/images/anime/1530/120110.webp?s=4aaac682a2a4727af927349fa2eb9260"
            alt="img"
            className={styles.animeImage}
          />

          <div className={styles.animeContent}>
            <h2 className={styles.title}>Overlord</h2>
            <div className={styles.genres}>
              <span className={styles.genre}>Action</span>
              <span className={styles.genre}>Adventure</span>
              <span className={styles.genre}>Fantasy</span>
            </div>
          </div>
        </div>
      </div> */}
    </div>
  );
}
