import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

// styles
import styles from "../../styles/Anime.module.css";

export async function getServerSideProps({ query }) {
  const { q: searchingQuery } = query;

  const res = await fetch(
    `http://api.jikan.moe/v4/anime?q=${searchingQuery}&limit=15&sfw=false`
  );

  const { data } = await res.json();
  if (!res.ok || data.length === 0) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      searchingQuery,
      data,
    },
  };
}

export default function SearchPage({ data, searchingQuery }) {
  const router = useRouter();
  console.log(data);
  return (
    <div>
      <Head>
        <title>search: {searchingQuery}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.sectionHeader}>
        <h1>Searching : {searchingQuery}</h1>
        <button
          onClick={() => router.back()}
          className="button"
          style={{ opacity: ".8" }}
        >
          Back
        </button>
      </div>
      <div className={styles.animesContainer}>
        {data.map((anime) => {
          return (
            <div className={styles.card} key={anime.mal_id}>
              <div className={styles.rating}>{anime.score}</div>

              <Image
                loading="lazy"
                style={{ objectFit: "cover", aspectRatio: "3/4" }}
                src={anime.images.jpg.large_image_url}
                alt={anime.title}
                width={150}
                height={200}
                layout="responsive"
                className={styles.animeImage}
              />

              <div className={styles.animeContent}>
                <Link href={`/anime/${anime.mal_id}`}>
                  <h2 className={styles.title}>{anime.title}</h2>
                </Link>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
