import Head from "next/head";

export default function About() {
  return (
    <div>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About Page</h1>

      <article>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor sed
          repudiandae nihil iusto illum voluptas reiciendis a, accusamus
          incidunt. Distinctio reiciendis quo, fugiat, officia possimus
          assumenda rem aspernatur error aperiam animi vitae beatae. Dolorum
          provident, eos voluptas porro aliquid possimus.
        </p>
      </article>
    </div>
  );
}
