import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ loading }) {
  return (
    <div>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home Page</h1>
      <Link href="/anime">
        <button className={styles.button}>To Anime List</button>
      </Link>
    </div>
  );
}
